package com.jbit.entity;

import java.util.Date;

public class AsAccountdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.systemconfigId
     *
     * @mbggenerated
     */
    private Integer systemconfigid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.accountMoney
     *
     * @mbggenerated
     */
    private Double accountmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.detailDateTime
     *
     * @mbggenerated
     */
    private Date detaildatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.id
     *
     * @return the value of as_accountdetail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.id
     *
     * @param id the value for as_accountdetail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.systemconfigId
     *
     * @return the value of as_accountdetail.systemconfigId
     *
     * @mbggenerated
     */
    public Integer getSystemconfigid() {
        return systemconfigid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.systemconfigId
     *
     * @param systemconfigid the value for as_accountdetail.systemconfigId
     *
     * @mbggenerated
     */
    public void setSystemconfigid(Integer systemconfigid) {
        this.systemconfigid = systemconfigid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.userId
     *
     * @return the value of as_accountdetail.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.userId
     *
     * @param userid the value for as_accountdetail.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.money
     *
     * @return the value of as_accountdetail.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.money
     *
     * @param money the value for as_accountdetail.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.accountMoney
     *
     * @return the value of as_accountdetail.accountMoney
     *
     * @mbggenerated
     */
    public Double getAccountmoney() {
        return accountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.accountMoney
     *
     * @param accountmoney the value for as_accountdetail.accountMoney
     *
     * @mbggenerated
     */
    public void setAccountmoney(Double accountmoney) {
        this.accountmoney = accountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.detailDateTime
     *
     * @return the value of as_accountdetail.detailDateTime
     *
     * @mbggenerated
     */
    public Date getDetaildatetime() {
        return detaildatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.detailDateTime
     *
     * @param detaildatetime the value for as_accountdetail.detailDateTime
     *
     * @mbggenerated
     */
    public void setDetaildatetime(Date detaildatetime) {
        this.detaildatetime = detaildatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.memo
     *
     * @return the value of as_accountdetail.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.memo
     *
     * @param memo the value for as_accountdetail.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}